### PR TITLE
fix landing responsiveness

### LINKED ISSUE #128: Mobile Responsiveness Landing
Image

Try to make the dragon work out by making the text smaller .this part is lowk cooked cos of the desktop design😭😭

There should also be more spacing on mobile for above mission statement 

Image

### PR DESCRIPTION
**Pull request by Sdrabla**
Starts to get iffy past 400px width
image

closes #128

### CODE REVIEW

**Review by agoel27 — CHANGES_REQUESTED** [review]
image

If we break each line into many p tags, we can get awkward text breaks on different screen widths. I included an image above for reference. Instead, try putting all the text into 1 p tag and use padding to restrict the text area.

image

I think the mission statement part would nicer if it was closer to the left side of screen on smaller screen sizes. Do you see how it is floating towards the center right now?

**Comment by Sdrabla** [comment]
image

**Review by stanleylew5 — CHANGES_REQUESTED** [review]
move the mission statement a lot more to the right on desktops so the dragon can be larger since it looks like this on my screen right now. 

image
 for mobile, make the text a whole lot smaller its absolutely massive right now on my side

image

**Comment by Sdrabla** [comment]
image

File: src/components/home/Landing.tsx [hunk 1]
```diff
@@ -1,44 +1,44 @@
 import Dragon from "@/public/home/Dragon.webp";
+import RightCloud from "@/public/home/RightCloud.svg";
 import Image from "next/image";
 const Landing = () => {
   return (
     <div>
-      <div className="relative mr-[10vw] border-r-8 border-csa-red-100 pr-[2vw] text-right">
-        <div className="font-lora mb-8 flex flex-col border-csa-red-100 text-6xl font-semibold text-csa-red-100">
+      <div className="px-25 relative mr-[10vw] border-r-8 border-csa-red-100 pr-5 text-right">
+        <div className="font-lora mb-8 border-csa-red-100 pl-20 text-right text-4xl font-semibold text-csa-red-100 sm:text-5xl">
```
Comment (stanleylew5) [inline src/components/home/Landing.tsx:8]: use a more responsive unit other than pl-20, 20 is lowk kinda big. also you can do flex flex-col here so the Chinese Student Association text stacks on top of each other along with the text below that goes Social, cultural, etc.

File: src/components/home/Landing.tsx [hunk 2]
```diff
@@ -1,44 +1,44 @@
...
+          promote the Chinese American culture throughout the UCR and Riverside
+          communities.
+        </p>
+      </div>
       <div>
         <Image
           src={Dragon}
           alt="dragon"
-          className="absolute left-0 top-12 w-1/4 pt-7"
+          className="sm:top-15% absolute left-0 top-10 w-[25%] pt-20 sm:w-[20%]"
```
Comment (stanleylew5) [inline src/components/home/Landing.tsx:39]: paddign shouldn't do anything if the image is absolute so remove that

**Review by stanleylew5 — CHANGES_REQUESTED** [review]

File: src/components/home/Landing.tsx [hunk 3]
```diff
@@ -1,44 +1,44 @@
 import Dragon from "@/public/home/Dragon.webp";
+import RightCloud from "@/public/home/RightCloud.svg";
 import Image from "next/image";
 const Landing = () => {
   return (
     <div>
-      <div className="relative mr-[10vw] border-r-8 border-csa-red-100 pr-[2vw] text-right">
-        <div className="font-lora mb-8 flex flex-col border-csa-red-100 text-6xl font-semibold text-csa-red-100">
+      <div className="px-25 relative mr-[10vw] border-r-8 border-csa-red-100 pr-5 text-right">
```
[the remark this answers is not in the document]
Comment (Sdrabla) [reply src/components/home/Landing.tsx:7]: ended up not even needing it o7

**Comment by FelixMDM** [comment]
Fix some merge conflicts in Landing.tsx conflicting with the animation that was introduced, otherwise looks good
